### ISSUE TITLE
Color correction changes when picking up cube

### ISSUE THREAD

**Issue by ihpsm** [SecondFaceSoftware/PortalRevolution-Issues#236]
### Game Version

Version 1.6.1

### Describe the bug

When i pickup the cube the whole game starts looking darker and with stronger contrast. The moment i release the cube it comes back to normal. Tried turning off and on color correction and HDR tonemapping options but it doesn't help.
Native build doesn't start, when trying to start the game via proton it says that my gpu isn't directx 11 compatible. I think that's because my gpu only supports vulkan 1.2, not 1.3. So to run the game i force proton 9 to translate dx11 into opengl instead of vulkan by using PROTON_USE_WINED3D=1 launch parameter.

### To Reproduce

Proton version is 9
PROTON_USE_WINED3D=1 %command% launch parameter
Start the game
Pickup any cube.

### Expected behavior

Visuals of the game remain the same while manipulating the cube.

### Screenshots

https://github.com/user-attachments/assets/d4071273-744c-433e-a023-3c465a240b46

### Desktop

OS: Arch Linux
CPU: Intel Core i5 4340m
GPU: NVIDIA Quadro K2100m (kepler architecture, latest supported driver version is 470.xx)
RAM: 16GB DDR3 1600 mhz dual channel
Game installed on HDD

**Comment by StefanH-AT** [comment]
I have no idea what's causing the weird desaturated look when you're not holding the cube. But since you're hacking your graphics driver to do stuff it's not supposed to do I don't deem this an issue on our end or something we can fix. The minimum specs are available on the steam store page; if your computer doesn't meet them, I can't give you support
